## This chart relies on the common library chart from bjw-s
## You can find it at https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
## Refer there for more detail about the supported values

image:
  repository: docmost/docmost
  tag: 0.7.0
  pullPolicy: IfNotPresent

#controller:
  # -- Set the controller upgrade strategy
#  strategy: RollingUpdate

# Service settings
service:
  main:
    enabled: true
    type: ClusterIP
    ports:
      http:
        port: 3000
        targetPort: 3000

# Ingress settings
ingress:
  main:
    enabled: false
#    className: nginx
#    hosts:
#      - host: docmost-app.local
#        paths:
#          - path: /
#            pathType: Prefix

# If storage type is S3, set persistence.data.enabled to false
docmost:
  secretKey: ""
  storage:
    type: local
#  s3:
#    accessKey: ""
#    secretKey: ""
#    region: ""
#    bucket: ""
#    endpoint: ""
#    pathStyle:

persistence:
  # -- Configure persistence settings for the chart under this key.
  data:
    enabled: true
    retain: true
#   storageClass: ""
    accessMode: ReadWriteOnce
    size: 5Gi
#   existingClaim: ""

# Dependencies

postgresql:
  enabled: true
  auth:
    database: docmost
    username: docmost
    postgresPassword: adminpassword
    password: docmostpass
#  primary:
#    persistence:
#      existingClaim: docmost-postgresql

redis:
  enabled: true
  image:
    tag: 7.2
  architecture: standalone
  auth:
    enabled: false
#  master:
#    persistence:
#      existingClaim: docmost-redis
