apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  {{- if .Values.docmost.secret }}
  SECRET_KEY: {{ .Values.docmost.secretKey }}
  {{- else }}
  SECRET_KEY: {{ default (randAlphaNum 64) | b64enc }}
  {{- end }}
