apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  {{- with .Values.docmost.s3 }}
  accessKey: {{ .accessKey | b64enc | quote }}
  secretKey: {{ .secretKey | b64enc | quote }}
  {{- end }}
