apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  appSecret: {{- $existing := (lookup "v1" "Secret" .Release.Namespace (printf "%s-app" .Release.Name)) -}}
             {{- if $existing }}
             {{ index $existing.data "appSecret" }}
             {{- else }}
             {{ (default (randAlphaNum 64) .Values.docmost.appSecret) | b64enc | quote }}
             {{- end }}
  
  {{- if (eq .Values.docmost.storage.type "s3") }}
  {{- with .Values.docmost.s3 }}
  accessKey: {{ .accessKey | b64enc | quote }}
  secretKey: {{ .secretKey | b64enc | quote }}
  {{- end }}
  {{- end }}

  {{- if and .Values.docmost.mail.enabled (eq .Values.docmost.mail.type "smtp")}}
  {{- with .Values.docmost.mail.smtp }}
  smtp-username: {{ .username | b64enc | quote }}
  smtp-password: {{ .password | b64enc | quote }}
  {{- end }}
  {{- end }}
  
  {{- if and .Values.docmost.mail.enabled (eq .Values.docmost.mail.type "postmark")}}
  postmark-token: {{ .Values.docmost.mail.postmark.token | b64enc | quote }}
  {{- end }}